name: Sync

on: [push]

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Push to remote repo
      run: |
        git log -1
        git push --mirror --force --repo https://${{ secrets.PAT_USERNAME }}:${{ secrets.PAT_PASSWORD }}@dev.azure.com/martinwoodward/mirrored/_git/mirrored
        
