name: Sync

on: [push]

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Push to remote repo
      run: |
        echo Last Commit
        git log -1
        echo Force push to server
        git push --force --repo https://${{ secrets.PAT_USERNAME }}:${{ secrets.PAT_PASSWORD }}@dev.azure.com/martinwoodward/mirrored/_git/mirrored --follow-tags
        
